name: Build Android TV ROM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java Development Kit
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip kpartx python3-mako python-is-python3

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "export PATH=\$PATH:~/bin" >> $GITHUB_ENV

      - name: Initialize repo
        run: |
          mkdir -p android-tv
          cd android-tv
          repo init -u git://github.com/LineageOS/android.git -b cm-14.1
          curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi3.xml \
            -O -L https://raw.githubusercontent.com/bhnibir/android-tv-build/cm-14.1/manifest_brcm_rpi3.xml

      - name: Sync repositories
        run: |
          cd android-tv
          repo sync

      - name: Apply patches
        run: |
          cd android-tv/path/to/project
          git am patchname.patch

      - name: Set up build environment
        run: |
          cd android-tv
          source build/envsetup.sh
          lunch lineage_rpi3-userdebug

      - name: Build the ROM
        run: |
          cd android-tv
          make -j$(nproc) kernel ramdisk systemimage

      - name: Create writable image
        run: |
          cd android-tv/device/brcm/rpi3
          sudo ./mkimg.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-tv-rom
          path: android-tv/device/brcm/rpi3/output.img
